//TRABAJO REALIZADO POR JULIAN GONZALEZ HERNANDEZ
package formularios;

import conexionbasedatos.Conection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jlio
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActulizar = new javax.swing.JButton();
        btnActulizar1 = new javax.swing.JButton();
        btnActulizar2 = new javax.swing.JButton();
        btnActulizar3 = new javax.swing.JButton();
        btnActulizar4 = new javax.swing.JButton();
        btnActulizar5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInicio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnActulizar.setText("Tabla Cliente");
        btnActulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizarActionPerformed(evt);
            }
        });

        btnActulizar1.setText("Tabla Vehiculo");
        btnActulizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizar1ActionPerformed(evt);
            }
        });

        btnActulizar2.setText("Tabla Intencion Compra");
        btnActulizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizar2ActionPerformed(evt);
            }
        });

        btnActulizar3.setText("Tabla Bicicleta");
        btnActulizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizar3ActionPerformed(evt);
            }
        });

        btnActulizar4.setText("Tabla Proveedor");
        btnActulizar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizar4ActionPerformed(evt);
            }
        });

        btnActulizar5.setText("Tabla Motocicleta");
        btnActulizar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActulizar5MouseClicked(evt);
            }
        });
        btnActulizar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizar5ActionPerformed(evt);
            }
        });

        jLabel1.setText("CONSULTAS PERSONALIZADAS");

        jButton1.setText("Consulta 1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consulta 3");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Consulta 2");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Consulta 6");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Consulta 4");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Consulta 5");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        tablaInicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton6))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActulizar3)
                            .addComponent(jButton3)
                            .addComponent(btnActulizar4)
                            .addComponent(btnActulizar5)))
                    .addComponent(jLabel1)
                    .addComponent(btnActulizar)
                    .addComponent(btnActulizar1)
                    .addComponent(btnActulizar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActulizar)
                            .addComponent(btnActulizar3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActulizar4)
                            .addComponent(btnActulizar1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActulizar5)
                            .addComponent(btnActulizar2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton2)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(jButton4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizarActionPerformed
        Cliente a = new Cliente();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActulizarActionPerformed

    private void btnActulizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizar1ActionPerformed
        Vehiculo a = new Vehiculo();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActulizar1ActionPerformed

    private void btnActulizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizar2ActionPerformed
        IntencionCompra a = new IntencionCompra();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActulizar2ActionPerformed

    private void btnActulizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizar3ActionPerformed
        Bicicleta a = new Bicicleta();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActulizar3ActionPerformed

    private void btnActulizar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizar4ActionPerformed
        Proveedor a = new Proveedor();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActulizar4ActionPerformed

    private void btnActulizar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizar5ActionPerformed

    }//GEN-LAST:event_btnActulizar5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        consulta1();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        consulta2();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        consulta3();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        consulta4();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        consulta5();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        consulta6();
    }//GEN-LAST:event_jButton4MouseClicked

    private void btnActulizar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActulizar5MouseClicked
        Motocicleta a = new Motocicleta();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActulizar5MouseClicked
 Connection conn = Conection.conectarDB();
 
     public void consulta1(){
        String[] titulos= {"nombreFabricante"};
        String[] registros = new String[1];
        
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT Vehiculo.nombreFabricante FROM Vehiculo ORDER BY Vehiculo.nombreFabricante;";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("nombreFabricante");                
                modelo.addRow(registros);
            }
            tablaInicio.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Consulta 1"+ e.getMessage());
        }
        
    }
     
     public void consulta2(){
        String[] titulos= {"nombreFabricante", "precioUnitario", "anioConstruccion"};
        String[] registros = new String[3];
        
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT nombreFabricante, precioUnitario, anioConstruccion FROM vehiculo	JOIN bicicleta	ON idBicicleta= idVehiculo and anioConstruccion>=2019 ORDER BY Vehiculo.nombreFabricante;";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("nombreFabricante"); 
                registros[1]=rs.getString("precioUnitario"); 
                registros[2]=rs.getString("anioConstruccion"); 
                modelo.addRow(registros);
            }
            tablaInicio.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Consulta 2"+ e.getMessage());
        }
        
    }
     
     public void consulta3(){
        String[] titulos= {"nombreFabricante"};
        String[] registros = new String[1];
        
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT nombreFabricante	FROM  motocicleta m	JOIN proveedor p ON m.idProveedor = p.idProveedor JOIN vehiculo v ON  idVehiculo = idMotocicleta WHERE p.nombre like '%Auteco%';";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("nombreFabricante");
                modelo.addRow(registros);
            }
            tablaInicio.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Consulta 3"+ e.getMessage());
        }
        
    }
     
     public void consulta4(){
        String[] titulos= {"nombreFabricante"};
        String[] registros = new String[1];
        
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT nombreFabricante	FROM intencioncompra i JOIN vehiculo v  ON i.idVehiculo= v.idVehiculo  WHERE aliasCliente LIKE '%lucky%' order by nombreFabricante;";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("nombreFabricante"); 

                modelo.addRow(registros);
            }
            tablaInicio.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Consulta 4"+ e.getMessage());
        }
        
    }
     
     public void consulta5(){
        String[] titulos= {"aliasCliente", "nombres", "apellidos"};
        String[] registros = new String[3];
        
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT  c.aliasCliente, nombres, apellidos	FROM cliente c  JOIN intencioncompra i ON c.aliasCliente = i.aliasCliente JOIN vehiculo v ON i.idVehiculo = v.idVehiculo WHERE nombreFabricante LIKE '%Yeti%';";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("aliasCliente"); 
                registros[1]=rs.getString("nombres"); 
                registros[2]=rs.getString("apellidos"); 
                modelo.addRow(registros);
            }
            tablaInicio.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Consulta 5"+ e.getMessage());
        }
        
    }
     
     public void consulta6(){
        String[] titulos= {"COUNT(*)"};
        String[] registros = new String[1];
        
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT COUNT(*)	FROM bicicleta	WHERE anioConstruccion >= 2019;";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("COUNT(*)");  
                modelo.addRow(registros);
            }
            tablaInicio.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Consulta 6"+ e.getMessage());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActulizar;
    private javax.swing.JButton btnActulizar1;
    private javax.swing.JButton btnActulizar2;
    private javax.swing.JButton btnActulizar3;
    private javax.swing.JButton btnActulizar4;
    private javax.swing.JButton btnActulizar5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInicio;
    // End of variables declaration//GEN-END:variables
}
