/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexionbasedatos.Conection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jlio
 */
public class IntencionCompra extends javax.swing.JFrame {

    /**
     * Creates new form IntencionCompra
     */
    public IntencionCompra() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActulizar = new javax.swing.JButton();
        txtidIntencionCompra = new javax.swing.JTextField();
        txtaliasCliente = new javax.swing.JTextField();
        txtidVehiculo = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaIntencionCompra = new javax.swing.JTable();
        btnNuevo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("idIntencionCompra:");

        jLabel2.setText("aliasCliente:");

        jLabel3.setText("idVehiculo:");

        jLabel4.setText("fecha:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActulizar.setText("Actualizar");
        btnActulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizarActionPerformed(evt);
            }
        });

        txtaliasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaliasClienteActionPerformed(evt);
            }
        });

        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        jLabel8.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        tablaIntencionCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaIntencionCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaIntencionCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaIntencionCompra);

        btnNuevo1.setText("Volver al Inicio");
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(txtidVehiculo)
                            .addComponent(txtaliasCliente)
                            .addComponent(txtidIntencionCompra)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnNuevo)
                                .addGap(30, 30, 30)
                                .addComponent(btnGuardar)
                                .addGap(51, 51, 51)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(btnActulizar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(btnNuevo1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidIntencionCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtaliasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtidVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnNuevo)
                            .addComponent(btnEliminar)
                            .addComponent(btnActulizar))
                        .addGap(33, 33, 33)
                        .addComponent(btnNuevo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCajas();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        crearIntencionCompra();
        limpiarCajas ();
        mostrar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarRegistro();
        limpiarCajas ();
        mostrar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizarActionPerformed
        Actualizar();
        limpiarCajas ();
        mostrar();
    }//GEN-LAST:event_btnActulizarActionPerformed

    private void txtaliasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaliasClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaliasClienteActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

     public void crearIntencionCompra(){
        try{
            String sql = "INSERT INTO IntencionCompra (idIntencionCompra, aliasCliente, idVehiculo, fecha) VALUES (? ,? , ? , ?)";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString (1 , txtidIntencionCompra.getText());
            statement.setString(2 , txtaliasCliente.getText());
            statement.setString(3 , txtidVehiculo.getText());
            statement.setString(4 , txtfecha.getText());         

            statement.execute();
            JOptionPane.showMessageDialog(null, "Intencion compra Agregado");
            
            int rowsInserted = statement.executeUpdate();
        }catch(Exception ex){
            //JOptionPane.showMessageDialog(null, "Error insertando intencion compra"+ ex.getMessage());
        }
    }
    
    private void tablaIntencionCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIntencionCompraMouseClicked
        limpiarCajas();
        int filaSeleccionada = tablaIntencionCompra.rowAtPoint(evt.getPoint());

        txtidIntencionCompra.setText(tablaIntencionCompra.getValueAt(filaSeleccionada,0).toString());
        txtaliasCliente.setText(tablaIntencionCompra.getValueAt(filaSeleccionada,1).toString());
        txtidVehiculo.setText(tablaIntencionCompra.getValueAt(filaSeleccionada,2).toString());
        txtfecha.setText(tablaIntencionCompra.getValueAt(filaSeleccionada,3).toString());

        mostrar();
    }//GEN-LAST:event_tablaIntencionCompraMouseClicked

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        Inicio a = new Inicio();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        filtrar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    public void limpiarCajas (){
        txtidIntencionCompra.setText("");
        txtaliasCliente.setText("");
        txtidVehiculo.setText("");
        txtfecha.setText("");
    }
    
    public void Actualizar(){
        try{
            String dao = (String)txtidIntencionCompra.getText();
        
            String sql = "UPDATE IntencionCompra SET  aliasCliente=?, idVehiculo=?,fecha=? WHERE idIntencionCompra=?";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1 , txtaliasCliente.getText());
            statement.setString(2 , txtidVehiculo.getText());
            statement.setString(3 , txtfecha.getText());
            
            statement.setString(4, dao);
            statement.execute();
            JOptionPane.showMessageDialog(null, "Intencion compra Editada");
            
            int rowsInserted = statement.executeUpdate();           
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error Editando Intencion compra"+ ex);
        }
    }
     
    public void filtrar(String valor){
        String[] titulos= {"idIntencionCompra", "aliasCliente", "idVehiculo", "fecha"};
        String[] registros = new String[4];
        
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT * FROM intencionCompra WHERE idIntencionCompra LIKE '%"+valor+"%'";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("idIntencionCompra");
                registros[1]=rs.getString("aliasCliente");
                registros[2]=rs.getString("idVehiculo");
                registros[3]=rs.getString("fecha");
                
                modelo.addRow(registros);
            }
            tablaIntencionCompra.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Intencion Compra"+ e.getMessage());
        }
        
    }
    
     public void eliminarRegistro(){
        String dao = txtidIntencionCompra.getText();
        
        try{
            Statement statement = conn.createStatement();
            String sql = "DELETE FROM intencionCompra WHERE idIntencionCompra LIKE '%"+dao+"%'";
            int n = statement.executeUpdate(sql);
            if (n>=0){
                JOptionPane.showMessageDialog(null,"intencion compra  Eliminado");
            }
        }catch (Exception e){
                JOptionPane.showMessageDialog(null,"intencion compra no Eliminado"+e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntencionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntencionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntencionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntencionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntencionCompra().setVisible(true);
            }
        });
    }
    Connection conn = Conection.conectarDB();
     public void mostrar(){
        String[] titulos= {"idIntencionCompra","aliasCliente","idVehiculo","fecha"};
        String[] registros = new String[4];
        DefaultTableModel modelo = new DefaultTableModel (null,titulos);
        String sql= "SELECT * FROM IntencionCompra";
        
        try {
            Statement statement= conn.createStatement();
            ResultSet rs= statement.executeQuery(sql);
            while (rs.next()){
                registros[0]=rs.getString("idIntencionCompra");
                registros[1]=rs.getString("aliasCliente");
                registros[2]=rs.getString("idVehiculo");
                registros[3]=rs.getString("fecha");
                
                modelo.addRow(registros);
            }
            tablaIntencionCompra.setModel(modelo);
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error Mostrando Intencion Compra"+ e.getMessage());
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActulizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaIntencionCompra;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtaliasCliente;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtidIntencionCompra;
    private javax.swing.JTextField txtidVehiculo;
    // End of variables declaration//GEN-END:variables
}
